// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentDelayApp.DataAccessLayer;

#nullable disable

namespace PaymentDelayApp.DataAccessLayer.Migrations
{
    [DbContext(typeof(PaymentDelayDbContext))]
    [Migration("20260410154101_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PaymentDelayApp.BusinessLayer.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DeliveryOrServiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Designation")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EcheanceFactureJours")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaymentAlert")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSettled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TtcAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceDate")
                        .HasDatabaseName("IX_Invoices_InvoiceDate");

                    b.HasIndex("IsSettled")
                        .HasDatabaseName("IX_Invoices_IsSettled");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("IX_Invoices_SupplierId");

                    b.HasIndex("IsPaymentAlert", "IsSettled")
                        .HasDatabaseName("IX_Invoices_IsPaymentAlert_IsSettled");

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("PaymentDelayApp.BusinessLayer.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Activite")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("AlertSeuilJours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FiscalId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ice")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("PaymentDelayApp.BusinessLayer.Models.Invoice", b =>
                {
                    b.HasOne("PaymentDelayApp.BusinessLayer.Models.Supplier", "Supplier")
                        .WithMany("Invoices")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PaymentDelayApp.BusinessLayer.Models.Supplier", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
